### ISSUE TITLE
Github files not appear

### ISSUE THREAD

**Issue by NikitaLiashenko** [mozilla-partners/pocket#17]
I've seen this problem multiple times. When I try to save to Pocket articles from Medium or something like files from Github, which were inside this link hadn't visualized properly. (screenshots are in attachment
![screenshot from 2017-07-31 13-12-53](https://user-images.githubusercontent.com/5084346/28773401-155a4c98-75f2-11e7-994f-296ff589fd11.png)
![screenshot from 2017-07-31 13-13-19](https://user-images.githubusercontent.com/5084346/28773402-155d7328-75f2-11e7-8e2b-fabcead09dda.png)

)

**Comment by ideashower** [comment]
Thanks for reporting @NikitaLiashenko! This bug is parser related (not covered by the code in this repo) so I'm going to close this issue. (I am filing it for the parser team though elsewhere internally)

**Comment by NikitaLiashenko** [comment]
@ideashower 
I'm sorry. I am not familiar with the codebase, so feel free to close and open same issue there.
Thanks.
